### ISSUE TITLE
Error: Missing getServerSnapshot, which is required for server-rendered content. Will revert to client rendering.

### ISSUE THREAD

**Issue by himsog** [jherr/fast-react-context#2]
### Steps to Replicate
* App/page must be server-rendered
* Open app and this error will show

### Screenshot
![Screen Shot 2022-10-23 at 1 08 54 PM](https://user-images.githubusercontent.com/116135345/197374938-d50be68d-e3d9-4ffa-ab64-2be3d9ab2c1f.png)

**Comment by jherr** [comment]
Fair enough, but this example is not NextJS, and the error you reported here is. To use this with NextJS you must implement the server side props snapshotting.
